local Defaults = 	{
		['zone'] =  		{
											['open'] = false,
											['fault'] = false,
											['alarm'] = false,
											['tamper'] = false
										},
		['partition'] = {
											['ready'] = false,
											['trouble'] = false,
											['exit_delay'] = false,
											['entry_delay'] = false,
											['armed'] = false,
											['armed_bypass'] = false,
											['alarm'] = false,
											['tamper'] = false,
											['chime'] = false,
											['trouble_led'] = false
										},
		['system'] = 		{
											['fire_key_alarm'] = false,
											['aux_key_alarm'] = false,
											['panic_key_alarm'] = false,
											['2wire_alarm'] = false,
											['battery_trouble'] = false,
											['ac_trouble'] = false,
											['system_bell_trouble'] = false,
											['system_tamper'] = false,
											['fire_trouble'] = false
										}
}


local ArmModes = 	{ [0] = 'Away', [1] = 'Stay', [2] = 'Zero Entry Away', [3] = 'Zero Entry Stay' }
									
										
local ResponseTypes = {
												[500] = { ['name'] = 'Command Acknowledge', ['description'] = 'A command has been received successfully.' },
												[501] = { ['name'] = 'Command Error', ['description'] = 'A command has been received with a bad checksum.' },
												[502] = { ['name'] = 'System Error %s' , ['description'] = 'An error has been detected.' },
												[505] = { ['name'] = 'Login Interaction' , ['description'] = 'Sent During Session Login Only.', ['handler'] = 'login' },
												[510] = { ['name'] = 'Keypad Led State' , ['description'] = 'Output when the TPI has detected a change of state in the Partition 1 keypad LEDs.' },
												[511] = { ['name'] = 'Keypad Led Flash State' , ['description'] = 'Output when the TPI has detected a change of state in the Partition 1 keypad LEDs as to whether to flash or not. Overrides 510. That is, if 511 says the PROGRAM LED is flashing, then it does not matter what 510 says.' },
												[550] = { ['name'] = 'Time/Date Broadcast' , ['description'] = 'Outputs the current security system time.' },
												[560] = { ['name'] = 'Ring Detected' , ['description'] = 'The Panel has detected a ring on the telephone line. Note: This command will only be issued if an ESCORT 5580xx module is present.' },
												[561] = { ['name'] = 'Indoor Temperature Broadcast' , ['description'] = 'If an ESCORT 5580TC is installed, and at least one ENERSTAT thermostat, this command displays the interior temperature and the thermostat number.' },
												[562] = { ['name'] = 'Outdoor Temperature Broadcast' , ['description'] = 'If an ESCORT 5580TC is installed, and at least one ENERSTAT thermostat, this command displays the exterior temperature and the thermostat number.' },
												[601] = { ['type'] = 'zone' , ['name'] = 'Partition {0[0]} Zone {0[1]}{0[2]}{0[3]} Alarm', ['description'] = 'A zone has gone into alarm.', ['handler'] = 'zone', ['status'] = { ['alarm'] = true } },
												[602] = { ['type'] = 'zone' , ['name'] = 'Partition {0[0]} Zone {0[1]}{0[2]}{0[3]} Alarm Restore' , ['description'] = 'A zone alarm has been restored.', ['handler'] = 'zone', ['status'] = { ['alarm'] = false } },
												[603] = { ['type'] = 'zone' , ['name'] = 'Partition {0[0]} Zone {0[1]}{0[2]}{0[3]} Tamper' , ['description'] = 'A zone has a tamper condition.', ['handler'] = 'zone', ['status'] = { ['tamper'] = true } },
												[604] = { ['type'] = 'zone' , ['name'] = 'Partition {0[0]} Zone {0[1]}{0[2]}{0[3]} Tamper Restore' , ['description'] = 'A zone tamper condition has been restored.', ['handler'] = 'zone', ['status'] = { ['tamper'] = false } },
												[605] = { ['type'] = 'zone' , ['name'] = 'Zone %s Fault' , ['description'] = 'A zone has gone into alarm.', ['status'] = { ['fault'] = true } },
												[606] = { ['type'] = 'zone' , ['name'] = 'Zone %s Fault Restore' , ['description'] = 'A zone fault condition has been restored.', ['status'] = { ['fault'] = false } },
												[609] = { ['type'] = 'zone' , ['name'] = 'Zone %s Open' , ['description'] = 'General status of the zone.', ['status'] = { ['open'] = true } },
												[610] = { ['type'] = 'zone' , ['name'] = 'Zone %s Restored' , ['description'] = 'General status of the zone.', ['status'] = { ['open'] = false } },
												[615] = { ['name'] = 'Envisalink Zone Timer Dump' , ['description'] = "This command contains the raw zone timers used inside the Envisalink. The dump is a 256 character packed HEX string representing 64 UINT16 (little endian) zone timers. Zone timers count down from 0xFFFF (zone is open) to 0x0000 (zone is closed too long ago to remember). Each 'tick' of the zone time is actually 5 seconds so a zone timer of 0xFFFE means '5 seconds ago'. Remember, the zone timers are LITTLE ENDIAN so the above example would be transmitted as FEFF." },
												[616] = { ['name'] = 'Bypassed Zones Bitfield Dump', ['description'] = "This command is issued upon leaving Zone Bypass programming (*1 on the keypad). It is a 16 character HEX string representing an 8 byte bitfield. This bitfield indicates which zones are currently in bypass. A '1' indicates the zone is in bypass. The lower 8 zones are in the first position of the bitfield. The developer can force this dump by using the keystring commands to enter and leave zone bypassing. i.e. '*1#'" },
												[620] = { ['name'] = 'Duress Alarm', ['description'] = 'A duress code has been entered on a system keypad.' },
												[621] = { ['type'] = 'system', ['name'] = '[F] Key Alarm', ['description'] = 'A Fire key alarm has been detected.', ['status'] = { ['fire_key_alarm'] = true } },
												[622] = { ['type'] = 'system', ['name'] = '[F] Key Alarm', ['description'] = 'A Fire key alarm has been restored (sent automatically).', ['status'] = { ['fire_key_alarm'] = false } },
												[623] = { ['type'] = 'system', ['name'] = '[A] Key Alarm', ['description'] = 'An Auxillary key alarm has been detected.', ['status'] = { ['aux_key_alarm'] = true} },
												[624] = { ['type'] = 'system', ['name'] = '[A] Key Alarm', ['description'] = 'An Auxillary key alarm has been restored (sent automatically).', ['status'] = { ['aux_key_alarm'] = false } },
												[625] = { ['type'] = 'system', ['name'] = '[P] Key Alarm', ['description'] = 'A Panic key alarm has been detected.', ['status'] = { ['panic_key_alarm'] = true } },
												[626] = { ['type'] = 'system', ['name'] = '[P] Key Alarm', ['description'] = 'A Panic key alarm has been restored (sent automatically).', ['status'] = { ['panic_key_alarm'] = false } },
												[631] = { ['type'] = 'system', ['name'] = '2-Wire Smoke/Aux Alarm', ['description'] = 'A 2-wire smoke/Auxiliary alarm has been activated.', ['status'] = { ['2wire_alarm'] = true } },
												[632] = { ['type'] = 'system', ['name'] = '2-Wire Smoke/Aux Restore', ['description'] = 'A 2-wire smoke/Auxiliary alarm has been restored.', ['status'] = { ['2wire_alarm'] = false } },
												[650] = { ['type'] = 'partition', ['name'] = 'Partition %s Ready', ['description'] = 'Partition can now be armed (all zones restored, no troubles, etc). Also issued at the end of Bell Timeout if the partition was READY when an alarm occurred.', ['status'] = { ['ready'] = true, ['pgm_output'] = false } },
												[651] = { ['type'] = 'partition', ['name'] = 'Partition %s Not Ready', ['description'] = 'Partition cannot be armed (zones open, trouble present, etc).', ['status'] = { ['ready'] = false } },
												[652] = { ['type'] = 'partition', ['name'] = 'Partition %s Armed Mode %s', ['description'] = 'Partition has been armed - sent at the end of exit delay Also sent after an alarm if the Bell Cutoff Timer expires Mode is appended to indicate whether the partition is armed AWAY, STAY, ZERO-ENTRY-AWAY, or ZERO-ENTRY-STAY.', ['handler'] = 'partition', ['status'] = { ['armed'] = true, ['exit_delay'] = false } },
												[653] = { ['type'] = 'partition', ['name'] = 'Partition %s Ready - Force Arming Enabled', ['description'] = 'Partition can now be armed (all zones restored, no troubles, etc). Also issued at the end of Bell Timeout if the partition was READY when an alarm occurred.', ['status'] = { ['ready'] = true } },
												[654] = { ['type'] = 'partition', ['name'] = 'Partition %s In Alarm', ['description'] = 'A partition is in alarm.', ['status'] = { ['alarm'] = true } },
												[655] = { ['type'] = 'partition', ['name'] = 'Partition %s Disarmed', ['description'] = 'A partition has been disarmed.', ['status'] = { ['alarm'] = false, ['armed'] = false, ['exit_delay'] = false, ['entry_delay'] = false } },
												[656] = { ['type'] = 'partition', ['name'] = 'Partition %s Exit Delay in Progress', ['description'] = 'A partition is in Exit Delay.', ['status'] = { ['exit_delay'] = true } },
												[657] = { ['type'] = 'partition', ['name'] = 'Partition %s Entry Delay in Progress', ['description'] = 'A partition is in Entry Delay.', ['status'] = { ['entry_delay'] = true } },
												[658] = { ['type'] = 'partition', ['name'] = 'Partition %s Keypad Lock-out', ['description'] = 'A partition is in Keypad Lockout due to too many failed user code attempts.'},
												[659] = { ['type'] = 'partition', ['name'] = 'Partition %s Failed to Arm', ['description'] = 'An attempt to arm the partition has failed.'},
												[660] = { ['type'] = 'partition', ['name'] = 'Partition %s PGM Output is in Progress', ['description'] = '*71, *72, *73, or *74 has been pressed.', ['status']= { ['pgm_output'] = true } },
												[663] = { ['type'] = 'partition', ['name'] = 'Partition %s Chime Enabled', ['description'] = 'The door chime feature has been enabled.', ['status'] = { ['chime'] = true } },
												[664] = { ['type'] = 'partition', ['name'] = 'Partition %s Chime Disabled', ['description'] = 'The door chime feature has been disabled.', ['status'] = { ['chime'] = false } },
												[670] = { ['type'] = 'partition', ['name'] = 'Partition %s Invalid Access Code', ['description'] = 'Invalid Access Code.' },
												[671] = { ['type'] = 'partition', ['name'] = 'Partition %s Function Not Available', ['description'] = 'A partition is in Entry delay.' },
												[672] = { ['type'] = 'partition', ['name'] = 'Partition %s Failure to Arm', ['description'] = 'An attempt was made to arm the partition and it failed.' },
												[673] = { ['type'] = 'partition', ['name'] = 'Partition %s is Busy', ['description'] = 'The partition is busy (another keypad is programming or an installer is programming).' },
												[674] = { ['type'] = 'partition', ['name'] = 'Partition %s System Arming in Progress', ['description'] = 'This system is auto-arming and is in arm warning delay.' },
												[680] = { ['name'] = 'System in installers mode', ['description'] = 'System has entered installers mode' },
												[700] = { ['type'] = 'partition', ['name'] = 'Partition %s User %s Closing', ['description'] = 'A partition has been armed by a user - sent at the end of exit delay.', ['handler'] = 'partition', ['status'] = { ['armed'] = true, ['exit_delay'] = false } },
												[701] = { ['type'] = 'partition', ['name'] = 'Partition %s Special Closing', ['description'] = 'A partition has been armed by one of the following methods= Quick Arm, Auto Arm, Keyswitch, DLS software, Wireless Key.', ['status'] = { ['armed'] = true, ['exit_delay'] = false } },
												[702] = { ['type'] = 'partition', ['name'] = 'Partition %s Partial Closing', ['description'] = 'A partition has been armed but one or more zones have been bypassed.', ['status'] = { ['armed'] = true, ['exit_delay'] = false } },
												[750] = { ['type'] = 'partition', ['name'] = 'Partition %s User %s Opening', ['description'] = 'A partition has been disarmed by a user.', ['handler'] = 'partition', ['status'] = { ['armed'] = false, ['entry_delay'] = false } },
												[751] = { ['type'] = 'partition', ['name'] = 'Partition %s Special Opening', ['description'] = 'A partition has been disarmed by one of the following methods= Keyswitch, DLS software, Wireless Key.',  ['status'] = { ['armed'] = false, ['entry_delay'] = false } },
												[800] = { ['type'] = 'system', ['name'] = 'Panel Battery Trouble', ['description'] = 'The panel has a low battery.', ['status'] = { ['battery_trouble'] = true } },
												[801] = { ['type'] = 'system', ['name'] = 'Panel Battery Trouble Restore', ['description'] = "The panel's low battery has been restored.", ['status'] = { ['battery_trouble'] = false } },
												[802] = { ['type'] = 'system', ['name'] = 'Panel AC Trouble', ['description'] = 'AC power to the panel has been removed.', ['status'] = { ['ac_trouble'] = true } },
												[803] = { ['type'] = 'system', ['name'] = 'Panel AC Restore', ['description'] = 'AC power to the panel has been restored.', ['status'] = { ['ac_trouble'] = false } },
												[806] = { ['type'] = 'system', ['name'] = 'System Bell Trouble', ['description'] = 'An open circuit has been detected across the bell terminals.', ['status'] = { ['system_bell_trouble'] = true } },
												[807] = { ['type'] = 'system', ['name'] = 'System Bell Trouble Restoral', ['description'] = 'The bell trouble has been restored.', ['status'] = { ['system_bell_trouble'] = false } },
												[814] = { ['name'] = 'FTC Trouble', ['description'] = 'The panel has failed to communicate successfully to the monitoring.'},
												[816] = { ['name'] = 'Buffer Near Full', ['description'] = "Sent when the panel's Event Buffer is 75% full from when it was last uploaded to DLS."},
												[829] = { ['type'] = 'system', ['name'] = 'General System Tamper', ['description'] = 'A tamper has occurred with one of the following modules= Zone Expander, PC5132, PC5204, PC5208, PC5400, PC59XX, LINKS 2X50, PC5108L, PC5100, PC5200.', ['status'] = { ['system_tamper'] = true } },
												[830] = { ['type'] = 'system', ['name'] = 'General System Tamper Restore', ['description'] = 'A general system Tamper has been restored.', ['status'] = { ['system_tamper'] = false } },
												[840] = { ['type'] = 'partition', ['name'] = 'Partition %s Trouble LED ON', ['description'] = 'This command shows the general trouble status that the trouble LED on a keypad normally shows. When ON, it means there is a trouble on this partition. This command when the LED transitions from OFF, to ON.', ['status'] = { ['trouble'] = true } },
												[841] = { ['type'] = 'partition', ['name'] = 'Partition %s Trouble LED OFF', ['description'] = 'This command shows the general trouble status that the trouble LED on a keypad normally shows. When the LED is OFF, this usually means there are no troubles present on this partition but certain modes will blank this LED even in the presence of a partition trouble. This command when the LED transitions from ON, to OFF.', ['status'] = { ['trouble'] = false } },
												[842] = { ['type'] = 'system', ['name'] = 'Fire Trouble Alarm', ['description'] = 'Fire Trouble Alarm', ['status'] = { ['fire_trouble'] = true } },
												[843] = { ['type'] = 'system', ['name'] = 'Fire Trouble Alarm Restore', ['description'] = 'Fire Trouble Alarm Restore', ['status'] = { ['fire_trouble'] = false } },
												[849] = { ['name'] = 'Verbose Trouble Status', ['description'] = 'This command is issued when a trouble appears on the system and roughly every 5 minutes until the trouble is cleared. The two characters are a bitfield (similar to 510,511). The meaning of each bit is the same as what you see on an LED keypad (see the user manual).' },
												[900] = { ['name'] = 'Code Required', ['description'] = 'This command will tell the API to enter an access code. Once entered, the 200 command will be sent to perform the required action. The code should be entered within the window time of the panel.' },
												[912] = { ['name'] = 'Command Output Pressed', ['description'] = 'This command will tell the API to enter an access code. Once entered, the 200 command will be sent to perform the required action. The code should be entered within the window time of the panel.' },
												[921] = { ['name'] = 'Master Code Required', ['description'] = 'This command will tell the API to enter a master access code. Once entered, the 200 command will be sent to perform the required action. The code should be entered within the window time of the panel.' },
												[922] = { ['name'] = 'Installers Code Required', ['description'] = 'This command will tell the API to enter an installers access code. Once entered, the 200 command will be sent to perform the required action. The code should be entered within the window time of the panel.' },
											}
		
local ErrorCodes = {
	[0] = 'No Error',
	[1] = 'RS-232 Receive Buffer Overrun (a command is received while another is still being processed)',
	[2] = 'RS-232 Receive Buffer Overflow',
	[3] = 'RS-232 Transmit Buffer Overflow',
	[10] = 'Keybus Transmit Buffer Overrun',
	[11] = 'Keybus Transmit Time Timeout',
	[12] = 'Keybus Transmit Mode Timeout',
	[13] = 'Keybus Transmit Keystring Timeout',
	[14] = 'Keybus Not Functioning (the S5401D cannot communicate with the security system)',
	[15] = 'Keybus Busy (Attempting to Disarm or Arm with user code)',
	[16] = 'Keybus Busy – Lockout (The panel is currently in Keypad Lockout – too many disarm attempts)',
	[17] = 'Keybus Busy – Installers Mode (Panel is in installers mode, most functions are unavailable)',
	[18] = 'Keybus Busy – General Busy (The partition requested is busy)',
	[20] = 'API Command Syntax Error',
	[21] = 'API Command Partition Error (Requested Partition is out of bounds)',
	[22] = 'API Command Not Supported',
	[23] = 'API System Not Armed (sent in response to a disarm command)',
	[24] = 'API System Not Ready to Arm (system is either busy, or already armed)',
	[25] = 'API Command Invalid Length',
	[26] = 'API User Code not Required',
	[27] = 'API Invalid Characters in Command (no alpha characters are allowed except for checksum)'
}

return {
	Defaults = Defaults,
	ArmModes = ArmModes,
	ResponseTypes = ResponseTypes,
	ErrorCodes = ErrorCodes
}
